[grid]
dew = 8000.
dns = 8000.
ewn = 761
nsn = 761
upn = 41
#nx_block = 32
#ny_block = 32
nx_block = 37
ny_block = 37
global_bc = 3
sigma = 1
sigma_file = 'sigma_levels.txt'

[grid_ocn]
nzocn = 30
dzocn = 60.
nbasin = 27

[time]
tstart = 0.
tend = 10000.
dt_input_option = 1
nsteps_per_year = 8
ndiag = 1
dm_dt_diag = 1
adaptive_cfl_threshold = 0.5  # subcycle advection when CFL > threshold
#idiag = 310    # Siple coast
#jdiag = 282
##idiag = 188    # Thwaites shelf near GL
##jdiag = 327
idiag = 310     # Ice stream C
jdiag = 307

[options]
dycore = 2              # 0 = glide, 1 = glam, 2 = glissade, 3 = felixFO
flow_law = 2            # 0 = constant, 2 = Paterson-Budd
evolution = 3           # 3 = remapping
temperature = 1         # 0 = use air temp for column temps, 1 = prognostic, 3 = enthalpy
temp_init = 3           # 1 = use air temp for init. column temps, 2 = linear w/ depth, 3 = advective-diffusive balance
marine_margin = 5       # 0 = no calving, 1 = remove all floating ice, 5 = no-advance calving, 8 = stress-based
limit_marine_cliffs = .false.
remove_icebergs = .true.
remove_isthmuses = .false.
calving_init = 1        # 1 = calve at initialization
basal_mass_balance = 1  # 1 = include bmlt in continuity
bmlt_float = 6          # 0 = no basal melt, 6 = thermal forcing
bmlt_float_thermal_forcing_param = 2  # 1 = ISMIP6 local, 2 = ISMIP6 nonlocal, 3 = ISMIP6 nonlocal slope
ocean_data_domain = 1                 # 1 = already extrapolated to cavities
gthf = 1                # 0 = constant, 1 = read from file
smb_input = 1           # 0 = acab (m/yr ice), 1 = smb (mm/yr w.e.)
dm_dt_diag = 1          # 1 = mass diagnostics in Gt/yr
enable_acab_dthck_dt_correction = .true.
restart = 1

[ho_options]
compute_blocks = 1                # 0 = all blocks, 1 = active only, 2 = inquire
which_ho_babc = 2                 # 4 = no-slip at bed, 2 = new pseudo-plastic, 7 = ZI, 9 = powerlaw, 11 = Schoof
which_ho_beta_limit = 0           # 1 = weight by f_ground before limiting
which_ho_coulomb_c = 1            # 0 = constant, 1 = invert for local Cc, 2 = read from file, 3 = invert for basin Cc
elevation_based_coulomb_c = .false.
which_ho_deltaT_ocn = 1           # 0 = zero dT_ocn, 1 = invert for local dT_ocn, 2 = read from file, 3 = invert for basin dT_ocn
deltaT_ocn_extrapolate = .true.   # if true, extrapolate dT_ocn to non-floating ice
which_ho_bwat = 0                 # 0 = no basal water, 2 = local basal till model, 3 = flux routing
which_ho_effecpress = 0           # 0 = overburden, 2 = macroporous sheet
which_ho_efvs = 2                 # 0 = constant, 2 = nonlinear eff. visc. w/ n = 3
which_ho_thermal_timestep = 0     # 0 = therm before transport, 1 = therm after transport, 2 = split
which_ho_resid = 4                # 4 = relative L2 norm
which_ho_sparse = 3               # 1 = SLAP GMRES, 4 = Trilinos for linear solver
which_ho_nonlinear = 1            # 0 = Picard, 1 = accelerated Picard
which_ho_gradient = 0             # 0 = centered
which_ho_gradient_margin = 1      # 1 = hybrid
which_ho_assemble_beta = 1        # 0 = standard; 1 = local
which_ho_assemble_bfric = 1       # 0 = standard; 1 = local
which_ho_assemble_taud = 1        # 0 = standard; 1 = local
which_ho_assemble_lateral = 1     # 0 = standard; 1 = local
which_ho_approx = 4               # 2 = BP, 4 = DIVA
which_ho_precond = 3              # 1 = diagonal, 2 = SIA, 3 = local tridiag, 4 = global_tridiag
which_ho_calving_front = 0        # 1 = subgrid calving front
which_ho_ground = 2               # 0 = no GLP, 1 = GLP, 2 = GLP with quadrants
which_ho_ground_bmlt = 1          # 0 = no GLP, 1 = GLP, floating fraction, 2 = GLP, zero grounded
which_ho_flotation_function = 2   # 2 = linear, 3 = linear with topg_raised
glissade_maxiter = 50
linear_solve_ncheck = 10
which_ho_vertical_remap = 1
which_ho_ice_age = 0
diva_slope_correction = .true.

[parameters]
flow_factor_ground = 1.0     # flow enhancement factor for grounded ice
flow_factor_float= 0.5       # flow enhancement factor for floating ice
ice_limit = 1.               # min ice thickness (m) for calc. mom. balance soln.
thck_gradient_ramp = 100.
marine_limit = -200          #
max_slope = 1.0              #
acab_factor = 1.0            # multiply input acab by this factor
bmlt_float_factor = 1.0      # multiply input bmlt_float by this factor
rhoi = 917.                  # Morlighem BedMachineAntarctica: 917
rhoo = 1027.                 # Morlighem BedMachineAntarctica: 1027
grav = 9.80616
shci = 2117.27
lhci = 3.337e5
trpt = 273.16
pmp_threshold = 1.e-3        # default = 1.e-3
pmp_offset = 5.0            # offset of initial Tbed from bpmp
beta_grounded_min = 1.0
beta_powerlaw_umax = 5000.
p_ocean_penetration = 0.5
ocean_p_timescale = 0.
calving_timescale = 0.
bmlt_cavity_h0 = 0.
pseudoplastic_q = 0.25
coulomb_c_min = 0.001
coulomb_c_const_hi = 0.20
inversion_thck_flotation_buffer = 2.0
inversion_thck_threshold = 1.0
inversion_babc_timescale = 400.
inversion_babc_thck_scale = 100.
inversion_babc_length_scale = 10000.
inversion_babc_relax_factor = 0.05
inversion_deltaT_ocn_timescale = 400.
inversion_deltaT_ocn_thck_scale = 100.
inversion_deltaT_ocn_length_scale = 10000.
inversion_deltaT_ocn_temp_scale = 2.0
inversion_basin_flotation_threshold = 100.
#calving_minthck = 50.
#tau_eigenconstant1 = 0.30
#tau_eigenconstant2 = 1.0
#stress_threshold = 75000.
thck_effective_min = 25.
thermal_forcing_basin_min = 0.2
#gamma0 =    11105.   # local MeanAnt
gamma0 =    25000.    # between MeanAnt and PIGL
#gamma0 =    49475.   # local PIGL
#gamma0 =    14433.   # nonlocal MeanAnt
#gamma0 =   159312.   # nonlocal PIGL
#gamma0 =  2062539.   # nonlocal-slope MeanAnt
#gamma0 =  5371969.   # nonlocal-slope PIGL

[basal_hydro]
ho_flux_routing_scheme = 0   # 0 = D8, 1 = Dinf (2 neighbors), 2 = FD8 (all neighbors)
btemp_scale = 2.0            # scale for freeze/thaw transition (degC)
effecpress_delta = 0.02      # fraction of overburden
bwat_threshold = 1.e-3       # water depth in m

[CF default]
comment = ISMIP6_Antarctica_8km
title = Antarctica spin-up

[CF input]
name = CISM3_initialization_AIS_08000.b_h_s_interp_median.m1for0bed.2025-03-03.nc
time = 1

[CF output]
variables = thk topg artm acab beta velnorm usurf lsurf btemp bpmp acab_applied bmlt_applied calving_rate grounded_mask floating_mask f_ground f_ground_cell f_flotation coulomb_c effecpress deltaT_ocn basin_number thermal_forcing_lsrf ice_domain_mask velo_sfc_obs dthck_dt dthck_dt_obs calving_mask flow_enhancement_factor ice_age bwat_diag bwatflx head bheatflx bfricflx bhydroflx uvel vvel wvel
name = out_Antarctica_8km.nc
frequency = 500.

[CF output]
variables = iareaf iareag imass imass_above_flotation total_smb_flux total_bmb_flux total_calving_flux total_gl_flux
name = out_Antarctica_8km.scalars.nc
frequency = 10.

[CF restart]
name = Antarctica_8km.restart.nc
variables = restart
frequency = 1000.
xtype = double
write_init = F
